"""
Deterministic database lookups — results are never generated by the LLM.
Currently implements:
  - OncoKB gene membership
  (GENIE/MSK prevalence requires institutional data access; placeholder provided)
"""

from __future__ import annotations

import logging
from typing import Optional, Set

import httpx

from src.config import settings

logger = logging.getLogger(__name__)

ONCOKB_GENES_URL = "https://www.oncokb.org/api/v1/genes"

_oncokb_gene_cache: Optional[Set[str]] = None


async def _load_oncokb_genes(client: httpx.AsyncClient) -> Set[str]:
    global _oncokb_gene_cache
    if _oncokb_gene_cache is not None:
        return _oncokb_gene_cache

    if not settings.oncokb_api_token:
        logger.warning("ONCOKB_API_TOKEN not set; in_oncokb will be None for all genes")
        _oncokb_gene_cache = set()
        return _oncokb_gene_cache

    headers = {
        "Authorization": f"Bearer {settings.oncokb_api_token}",
        "Accept": "application/json",
    }
    try:
        resp = await client.get(ONCOKB_GENES_URL, headers=headers, timeout=15.0)
        resp.raise_for_status()
        genes = resp.json()
        _oncokb_gene_cache = {g["hugoSymbol"] for g in genes if "hugoSymbol" in g}
        logger.info("Loaded %d OncoKB genes", len(_oncokb_gene_cache))
    except httpx.HTTPError as e:
        logger.error("Failed to load OncoKB genes: %s", e)
        _oncokb_gene_cache = set()

    return _oncokb_gene_cache


async def check_oncokb_membership(gene_symbol: str) -> Optional[bool]:
    """
    Returns True if in OncoKB, False if confirmed absent, None if unknown
    (no API token configured or lookup failed).
    """
    async with httpx.AsyncClient() as client:
        genes = await _load_oncokb_genes(client)

    if not genes and not settings.oncokb_api_token:
        return None

    return gene_symbol in genes


def get_msk_genie_prevalence(gene_symbol: str) -> Optional[str]:
    """
    Placeholder for MSK clinical sequencing / GENIE prevalence lookup.
    In production this queries the institutional data warehouse or a
    precomputed prevalence index. Returns None until that integration exists.
    """
    return None
